services:
  # Servicio PHP con Composer
  app:
    build: .
    container_name: php-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-ollama}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - DATA_SOURCE=${DATA_SOURCE:-github}
    networks:
      - ai-network
    depends_on:
      - db

  # Base de Datos con PGVector
  db:
    image: ankane/pgvector:latest # Imagen oficial con soporte de vectores
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-ai_db}
    networks:
      - ai-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # IA Local con Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    profiles: ["local-ai"]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
  postgres_data: